message = "enter some value"
days = 20
price = 4.99
valid_number = True
exit_input = False
list_of_days = [20, 40, 100, 20]
list_of_months = ["January", "February"]
set_of_days = {20, 49, 100 }  # no dublicates
days_and_unit_dictionary = {"days": 10, "unit": "hours"} # key: value